# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-13 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('sales', models.IntegerField(default=0)),
                ('tag', models.CharField(blank=True, max_length=75, null=True)),
                ('preview_image', models.ImageField(upload_to='img')),
                ('photo_set', models.FileField(upload_to=models.CharField(max_length=50))),
            ],
        ),
    ]
