# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-14 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoset',
            name='tag',
        ),
        migrations.AddField(
            model_name='photoset',
            name='price',
            field=models.FloatField(default=10),
        ),
    ]
