# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-14 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200414_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoset',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
    ]
