# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-14 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200414_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoset',
            name='photo_set',
            field=models.FileField(upload_to='photosets'),
        ),
    ]
